import{a as w,S,i as s}from"./assets/vendor-B1NZxHM-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();async function u(o,e=1){return(await w("https://pixabay.com/api/",{params:{key:"56141356-f92620e8971d743a7b3ebfb5b",q:`${o}`,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const q=new S(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}),h=document.querySelector(".gallery"),m=document.querySelector("#loader"),d=document.querySelector(".load-more-button");function g(o){const e=o.map(({webformatURL:n,largeImageURL:a,tags:t,likes:r,views:i,comments:L,downloads:v})=>`<li class="gallery-item">
          <a class="gallery-link-img" href="${a}">
            <img src="${n}" alt="${t}" class="gallery-img"/>
          </a>
          <div class="descr-container">
            <h3 class="gallery-likes"> Likes <br/> ${r} </h3>
            <h3 class="gallery-views"> Views <br/> ${i} </h3>
            <h3 class="gallery-comments"> Comments <br/> ${L} </h3>
            <h3 class="gallery-downloads"> Downloads <br/> ${v} </h3>
          </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",e),q.refresh()}function $(){h.innerHTML=""}function f(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function p(){d.classList.remove("hidden")}function M(){d.classList.add("hidden")}const E=document.querySelector("form"),P=document.querySelector('input[name="search-text"]');let l=1,c="";E.addEventListener("submit",x);d.addEventListener("click",B);function x(o){o.preventDefault(),c=P.value,c&&($(),f(),u(c,l).then(e=>{e.hits.length>0?g(e.hits):s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(e=>{s.error({title:"Error",message:`${e.message}`})}).finally(()=>{y(),l<b()?p():s.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."})}))}async function B(o){M(),f(),l++;try{const e=await u(c,l);e.hits.length>0?g(e.hits):s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch(e){s.error({title:"Error",message:`${e.message}`})}finally{y(),l<b()?p():s.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."})}}function b(){return Math.ceil(500/15)}
//# sourceMappingURL=index.js.map
