import{a as q,S as $,i as n}from"./assets/vendor-B1NZxHM-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function h(a,e=1){return(await q("https://pixabay.com/api/",{params:{key:"56141356-f92620e8971d743a7b3ebfb5b",q:`${a}`,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const M=new $(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}),m=document.querySelector(".gallery"),g=document.querySelector("#loader"),d=document.querySelector(".load-more-button");function y(a){const e=a.map(({webformatURL:o,largeImageURL:s,tags:t,likes:r,views:l,comments:v,downloads:S})=>`<li class="gallery-item">
          <a class="gallery-link-img" href="${s}">
            <img src="${o}" alt="${t}" class="gallery-img"/>
          </a>
          <div class="descr-container">
            <h3 class="gallery-likes"> Likes <br/> ${r} </h3>
            <h3 class="gallery-views"> Views <br/> ${l} </h3>
            <h3 class="gallery-comments"> Comments <br/> ${v} </h3>
            <h3 class="gallery-downloads"> Downloads <br/> ${S} </h3>
          </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",e),M.refresh()}function E(){m.innerHTML=""}function f(){g.classList.remove("hidden")}function p(){g.classList.add("hidden")}function b(){d.classList.remove("hidden")}function L(){d.classList.add("hidden")}const P=document.querySelector("form"),x=document.querySelector('input[name="search-text"]');let i=1,c="",u=null;P.addEventListener("submit",B);d.addEventListener("click",O);async function B(a){if(a.preventDefault(),c=x.value,!!c){E(),L(),f(),i=1;try{const e=await h(c,i);if(u=e.totalHits,e.hits.length>0)y(e.hits);else{n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}}catch(e){n.error({title:"Error",message:`${e.message}`})}finally{p(),i<w(u)?b():n.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."})}}}async function O(a){L(),f(),i++;try{const e=await h(c,i);if(e.hits.length>0)y(e.hits);else{n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"})}catch(e){n.error({title:"Error",message:`${e.message}`})}finally{p(),i<w(u)?b():n.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."})}}function w(a){return Math.ceil(a/15)}
//# sourceMappingURL=index.js.map
