import{a as $,S as M,i as l}from"./assets/vendor-CIF6YjI2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();async function m(a,e=1){return(await $("https://pixabay.com/api/",{params:{key:"56141356-f92620e8971d743a7b3ebfb5b",q:`${a}`,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const E=new M(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}),f=document.querySelector(".gallery"),y=document.querySelector("#loader"),g=document.querySelector(".load-more-button");function p(a){const e=a.map(({webformatURL:n,largeImageURL:i,tags:t,likes:r,views:c,comments:S,downloads:q})=>`<li class="gallery-item">
          <a class="gallery-link-img" href="${i}">
            <img src="${n}" alt="${t}" class="gallery-img"/>
          </a>
          <div class="descr-container">
            <h3 class="gallery-likes"> Likes <br/> ${r} </h3>
            <h3 class="gallery-views"> Views <br/> ${c} </h3>
            <h3 class="gallery-comments"> Comments <br/> ${S} </h3>
            <h3 class="gallery-downloads"> Downloads <br/> ${q} </h3>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",e),E.refresh()}function P(){f.innerHTML=""}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function w(){g.classList.remove("hidden")}function v(){g.classList.add("hidden")}const x=document.querySelector("form"),B=document.querySelector('input[name="search-text"]');let o=1,d="",u=null,s=null;x.addEventListener("submit",O);g.addEventListener("click",H);async function O(a){if(a.preventDefault(),d=B.value,!!d){P(),v(),b(),o=1;try{const e=await m(d,o);if(u=e.totalHits,s=e.hits.length,s>0)p(e.hits);else{l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}}catch(e){l.error({title:"Error",message:`${e.message}`})}finally{L(),a.target.reset(),o<h(u)&&s!==0?w():o>=h(u)&&s!==0&&l.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."})}}}async function H(a){v(),b(),o++;try{const e=await m(d,o);if(s=e.hits.length,s>0)p(e.hits);else{l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}catch(e){l.error({title:"Error",message:`${e.message}`})}finally{L(),o<h(u)&&s!==0?w():o>=h(u)&&s!==0&&l.warning({title:"Warning",message:"We're sorry, but you've reached the end of search results."})}}function h(a){return Math.ceil(a/15)}
//# sourceMappingURL=index.js.map
